# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\utente\PycharmProjects\pythonProject\mainCalendario.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from mainCalendarioSelezionato import Ui_SecondWindow

class Ui_Window(object):
    def openWindow(self):
        #apre l'altra pagina
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_SecondWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def moveData(self):
        row = self.tasksListWidget.currentRow()
        #assegna cosa a seconda finestra
        self.ui.labelReceiver.setText(row)


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(739, 499)
        self.calendarWidget = QtWidgets.QCalendarWidget(Form)
        self.calendarWidget.setGeometry(QtCore.QRect(70, 132, 411, 321))
        self.calendarWidget.setStyleSheet("    color: black;  \n"
"    background-color: light grey;  \n"
"    selection-background-color: rgb(126,126,126); \n"
"    selection-color black; \n"
"    alternate-background-color: rgb(196,196, 196); \n"
"font: 12pt;\n"
"")
        self.calendarWidget.setObjectName("calendarWidget")
        self.tasksListWidget = QtWidgets.QListWidget(Form, clicked = lambda: self.moveData())
        self.tasksListWidget.setGeometry(QtCore.QRect(510, 130, 211, 211))
        self.tasksListWidget.setStyleSheet("font:16pt")
        self.tasksListWidget.setObjectName("tasksListWidget")
        self.addButton = QtWidgets.QPushButton(Form)
        self.addButton.setGeometry(QtCore.QRect(510, 370, 211, 81))
        self.addButton.setStyleSheet("background-color: rgb(173,255,147)")
        self.addButton.setObjectName("addButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-50, 0, 861, 131))
        self.label.setStyleSheet("background: rgb(240,240,240);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(-30, 120, 861, 381))
        self.label_2.setStyleSheet("background: rgb(240,240,240);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.taskLineEdit = QtWidgets.QLineEdit(Form)
        self.taskLineEdit.setGeometry(QtCore.QRect(510, 100, 211, 20))
        self.taskLineEdit.setStyleSheet("font: 12;")
        self.taskLineEdit.setObjectName("taskLineEdit")
        self.saveButton = QtWidgets.QPushButton(Form)
        self.saveButton.setGeometry(QtCore.QRect(230, 100, 121, 23))
        self.saveButton.setObjectName("saveButton")
        self.infoButton = QtWidgets.QPushButton(Form, clicked = lambda: self.openWindow())
        self.infoButton.setGeometry(QtCore.QRect(660, 140, 51, 51))
        self.infoButton.setObjectName("infoButton")
        self.label.raise_()
        self.label_2.raise_()
        self.calendarWidget.raise_()
        self.tasksListWidget.raise_()
        self.addButton.raise_()
        self.taskLineEdit.raise_()
        self.saveButton.raise_()
        self.infoButton.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.addButton.setText(_translate("Form", "Crea Evento"))
        self.label.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">Calendario Eventi</span></p></body></html>"))
        self.label_2.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.saveButton.setText(_translate("Form", "SaveChangesTEMP"))
        self.infoButton.setText(_translate("Form", "INFO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Window()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
