# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\utente\PycharmProjects\IngSoft_Palestra\Calendario\mainCalendarioSelezionato.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SecondWindow(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(738, 497)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(-60, 120, 861, 381))
        self.label_2.setStyleSheet("background: rgb(240,240,240);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-60, 0, 861, 131))
        self.label.setStyleSheet("background: rgb(240,240,240);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.tasksListWidget = QtWidgets.QListWidget(Form)
        self.tasksListWidget.setGeometry(QtCore.QRect(510, 130, 211, 211))
        self.tasksListWidget.setStyleSheet("font:16pt")
        self.tasksListWidget.setObjectName("tasksListWidget")
        self.modifyButton = QtWidgets.QPushButton(Form)
        self.modifyButton.setGeometry(QtCore.QRect(510, 360, 101, 41))
        self.modifyButton.setStyleSheet("background-color: rgb(255,255,87)")
        self.modifyButton.setObjectName("modifyButton")
        self.deleteButton = QtWidgets.QPushButton(Form)
        self.deleteButton.setGeometry(QtCore.QRect(620, 360, 101, 41))
        self.deleteButton.setStyleSheet("background-color: rgb(255,77,77)")
        self.deleteButton.setObjectName("deleteButton")
        self.backButton = QtWidgets.QPushButton(Form)
        self.backButton.setGeometry(QtCore.QRect(510, 412, 211, 41))
        self.backButton.setStyleSheet("background-color: rgb(177,177,177)")
        self.backButton.setObjectName("backButton")
        self.labelReceiver = QtWidgets.QLabel(Form)
        self.labelReceiver.setGeometry(QtCore.QRect(80, 130, 401, 321))
        self.labelReceiver.setStyleSheet("background: light grey")
        self.labelReceiver.setText("")
        self.labelReceiver.setObjectName("labelReceiver")
        self.widgetName = QtWidgets.QWidget(Form)
        self.widgetName.setGeometry(QtCore.QRect(110, 180, 141, 21))
        self.widgetName.setStyleSheet("background: white")
        self.widgetName.setObjectName("widgetName")
        self.widgetTime = QtWidgets.QWidget(Form)
        self.widgetTime.setGeometry(QtCore.QRect(110, 250, 141, 21))
        self.widgetTime.setStyleSheet("background: white")
        self.widgetTime.setObjectName("widgetTime")
        self.widgetLocation = QtWidgets.QWidget(Form)
        self.widgetLocation.setGeometry(QtCore.QRect(310, 180, 141, 21))
        self.widgetLocation.setStyleSheet("background: white")
        self.widgetLocation.setObjectName("widgetLocation")
        self.widget_4 = QtWidgets.QWidget(Form)
        self.widget_4.setGeometry(QtCore.QRect(310, 250, 141, 21))
        self.widget_4.setStyleSheet("background: white")
        self.widget_4.setObjectName("widget_4")
        self.widget_5 = QtWidgets.QWidget(Form)
        self.widget_5.setGeometry(QtCore.QRect(110, 330, 341, 101))
        self.widget_5.setStyleSheet("background: white")
        self.widget_5.setObjectName("widget_5")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(146, 160, 71, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(356, 160, 51, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(150, 230, 61, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(340, 230, 81, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(250, 310, 61, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">Calendario Eventi</span></p></body></html>"))
        self.modifyButton.setText(_translate("Form", "MODIFICA"))
        self.deleteButton.setText(_translate("Form", "ELIMINA"))
        self.backButton.setText(_translate("Form", "INDIETRO"))
        self.label_3.setText(_translate("Form", "Nome Evento"))
        self.label_4.setText(_translate("Form", "Luogo"))
        self.label_5.setText(_translate("Form", "Orario"))
        self.label_6.setText(_translate("Form", "Organizzatore"))
        self.label_7.setText(_translate("Form", "Descrizione"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
